# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-02 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herolobemsg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='been_read',
            field=models.BooleanField(default=False),
        ),
    ]
